# Meta Data for SEO

## Homepage
title = "Mario Fasold"
titleSeparator = "-"
titleAddition = "My personal website"
footer = "© 2025 | <a href=\"/about\">About</a> | <a href=\"/blog/index.xml\">RSS</a>"


[social]
  twitter = "Mario Fasold"

# Images (@thulite/images)
[thulite_images]
  [thulite_images.defaults]
    decoding = "async" # sync, async, or auto (default)
    fetchpriority = "auto" # high, low, or auto (default)
    loading = "lazy" # eager or lazy (default)
    widths = [640, 768, 1024, 1366] # [640, 768, 1024, 1366, 1600, 1920] for example
    sizes = "auto" # 100vw (default), 75vw, or auto for example
    process = "" # "fill 1600x900" or "fill 2100x900" for example
    lqip = "16x webp q20" # "16x webp q20" or "21x webp q20" for example
    class = "img-fluid blur-up" # img-fluid (default)
