# Meta Data for SEO

## Homepage
title = "Mario Fasold"
titleSeparator = "-"
titleAddition = "My personal website"
footer = "© 2023 | <a href=\"/about\">About</a> | <a href=\"/blog/index.xml\">RSS</a>"
